# version: '3.8'

services:
  # Service Apache & PHP 7.4 keur Cccinfo
  web:
    build: .
    container_name: php74_cccinfo
    user: "1000:1000" # Nyingkahan error permission di Pop!_OS
    ports:
      - "8081:80" # Port luar 8081, moal tabrakan jeung Logsheet (8080)
    volumes:
      - .:/var/www/html
    restart: always
    networks:
      - default
      - db_hub # Nyambung ka jaringan luar tempat DB Logsheet aya

# Volumes dihapus sabab database geus pindah ka imah sabelah (Project 1)

networks:
  db_hub:
    external: true # Ngilu kana network external nu geus dijieun ku Project 1